function RTW_Sid2UrlHash() {
	this.urlHashMap = new Array();
	/* <Root>/r1 */
	this.urlHashMap["pid4:107"] = "pid4.c:112&pid4.h:94";
	/* <Root>/ym */
	this.urlHashMap["pid4:271"] = "pid4.c:113&pid4.h:95";
	/* <Root>/D_gain_Memory */
	this.urlHashMap["pid4:45"] = "pid4.h:84";
	/* <Root>/D_gain_Write */
	this.urlHashMap["pid4:46"] = "pid4.c:56";
	/* <Root>/DiscreteTf */
	this.urlHashMap["pid4:122"] = "msg=rtwMsg_notTraceable&block=pid4/DiscreteTf";
	/* <Root>/DiscreteTf2 */
	this.urlHashMap["pid4:123"] = "msg=rtwMsg_notTraceable&block=pid4/DiscreteTf2";
	/* <Root>/I_gain_Write */
	this.urlHashMap["pid4:42"] = "pid4.c:61";
	/* <Root>/I_gain_memory */
	this.urlHashMap["pid4:41"] = "pid4.h:85";
	/* <Root>/Kb_fact_Write */
	this.urlHashMap["pid4:69"] = "pid4.c:66";
	/* <Root>/N_coeff_Write */
	this.urlHashMap["pid4:103"] = "pid4.c:71";
	/* <Root>/N_fact_Memory */
	this.urlHashMap["pid4:102"] = "pid4.h:86";
	/* <Root>/P_gain_Memory */
	this.urlHashMap["pid4:48"] = "pid4.h:87";
	/* <Root>/P_gain_Write */
	this.urlHashMap["pid4:49"] = "pid4.c:76";
	/* <Root>/cKb */
	this.urlHashMap["pid4:67"] = "pid4.c:67";
	/* <Root>/cKd */
	this.urlHashMap["pid4:44"] = "pid4.c:57";
	/* <Root>/cKi */
	this.urlHashMap["pid4:43"] = "pid4.c:62";
	/* <Root>/cKp */
	this.urlHashMap["pid4:47"] = "pid4.c:77";
	/* <Root>/cN */
	this.urlHashMap["pid4:101"] = "pid4.c:72";
	/* <Root>/kb_fact_Memory */
	this.urlHashMap["pid4:68"] = "pid4.h:88";
	/* <Root>/sensor */
	this.urlHashMap["pid4:227"] = "msg=rtwMsg_notTraceable&block=pid4/sensor";
	/* <Root>/sume */
	this.urlHashMap["pid4:110"] = "pid4.c:111&pid4.h:66";
	/* <Root>/yc */
	this.urlHashMap["pid4:31"] = "pid4.c:150,153,156&pid4.h:100";
	/* <S2>/pulseGen */
	this.urlHashMap["pid4:111"] = "pid4.c:84,93,206&pid4.h:63,89";
	/* <S2>/pulseGenOffConstt */
	this.urlHashMap["pid4:114"] = "pid4.c:101";
	/* <S2>/pulseGenSw */
	this.urlHashMap["pid4:112"] = "pid4.c:100,109&pid4.h:65";
	/* <S2>/pulseSymConst */
	this.urlHashMap["pid4:118"] = "pid4.c:96";
	/* <S2>/sumW */
	this.urlHashMap["pid4:117"] = "pid4.c:95&pid4.h:64";
	/* <S4>/filter */
	this.urlHashMap["pid4:155"] = "msg=rtwMsg_notTraceable&block=pid4/pidstm/pidIdeal/filter";
	/* <S4>/integrate */
	this.urlHashMap["pid4:161"] = "msg=rtwMsg_notTraceable&block=pid4/pidstm/pidIdeal/integrate";
	/* <S4>/satPid */
	this.urlHashMap["pid4:162"] = "msg=rtwMsg_notTraceable&block=pid4/pidstm/pidIdeal/satPid";
	/* <S4>/sumI */
	this.urlHashMap["pid4:163"] = "msg=rtwMsg_notTraceable&block=pid4/pidstm/pidIdeal/sumI";
	/* <S4>/sumd */
	this.urlHashMap["pid4:164"] = "msg=rtwMsg_notTraceable&block=pid4/pidstm/pidIdeal/sumd";
	/* <S4>/sump */
	this.urlHashMap["pid4:165"] = "msg=rtwMsg_notTraceable&block=pid4/pidstm/pidIdeal/sump";
	/* <S4>/sums */
	this.urlHashMap["pid4:166"] = "msg=rtwMsg_notTraceable&block=pid4/pidstm/pidIdeal/sums";
	/* <S5>/filter */
	this.urlHashMap["pid4:191"] = "pid4.c:132,183&pid4.h:72,83";
	/* <S5>/integrate */
	this.urlHashMap["pid4:197"] = "pid4.c:120,180&pid4.h:68,82";
	/* <S5>/satPid */
	this.urlHashMap["pid4:198"] = "pid4.c:145,160";
	/* <S5>/sumI */
	this.urlHashMap["pid4:199"] = "pid4.c:177&pid4.h:81";
	/* <S5>/sumd */
	this.urlHashMap["pid4:200"] = "pid4.c:135&pid4.h:73";
	/* <S5>/sump */
	this.urlHashMap["pid4:201"] = "pid4.c:141&pid4.h:75";
	/* <S5>/sums */
	this.urlHashMap["pid4:202"] = "pid4.c:171&pid4.h:79";
	/* <S6>/Derivative Gain */
	this.urlHashMap["pid4:265:1666"] = "msg=rtwMsg_notTraceable&block=pid4/pidstm/pidBlock/PIDController/Derivative%20Gain";
	/* <S6>/Filter */
	this.urlHashMap["pid4:265:1668"] = "msg=rtwMsg_notTraceable&block=pid4/pidstm/pidBlock/PIDController/Filter";
	/* <S6>/Filter Coefficient */
	this.urlHashMap["pid4:265:1669"] = "msg=rtwMsg_notTraceable&block=pid4/pidstm/pidBlock/PIDController/Filter%20Coefficient";
	/* <S6>/Integral Gain */
	this.urlHashMap["pid4:265:1665"] = "msg=rtwMsg_notTraceable&block=pid4/pidstm/pidBlock/PIDController/Integral%20Gain";
	/* <S6>/Integrator */
	this.urlHashMap["pid4:265:1667"] = "msg=rtwMsg_notTraceable&block=pid4/pidstm/pidBlock/PIDController/Integrator";
	/* <S6>/Kb */
	this.urlHashMap["pid4:265:1673"] = "msg=rtwMsg_notTraceable&block=pid4/pidstm/pidBlock/PIDController/Kb";
	/* <S6>/Proportional Gain */
	this.urlHashMap["pid4:265:1664"] = "msg=rtwMsg_notTraceable&block=pid4/pidstm/pidBlock/PIDController/Proportional%20Gain";
	/* <S6>/Saturation */
	this.urlHashMap["pid4:265:1671"] = "msg=rtwMsg_notTraceable&block=pid4/pidstm/pidBlock/PIDController/Saturation";
	/* <S6>/Sum */
	this.urlHashMap["pid4:265:1663"] = "msg=rtwMsg_notTraceable&block=pid4/pidstm/pidBlock/PIDController/Sum";
	/* <S6>/SumD */
	this.urlHashMap["pid4:265:1670"] = "msg=rtwMsg_notTraceable&block=pid4/pidstm/pidBlock/PIDController/SumD";
	/* <S6>/SumI1 */
	this.urlHashMap["pid4:265:1674"] = "msg=rtwMsg_notTraceable&block=pid4/pidstm/pidBlock/PIDController/SumI1";
	/* <S6>/SumI2 */
	this.urlHashMap["pid4:265:1672"] = "msg=rtwMsg_notTraceable&block=pid4/pidstm/pidBlock/PIDController/SumI2";
	/* <S7>/D_gain */
	this.urlHashMap["pid4:137"] = "msg=rtwMsg_notTraceable&block=pid4/pidstm/pidIdeal/Kd/D_gain";
	/* <S7>/Derivative */
	this.urlHashMap["pid4:138"] = "msg=rtwMsg_notTraceable&block=pid4/pidstm/pidIdeal/Kd/Derivative";
	/* <S8>/I_gain */
	this.urlHashMap["pid4:142"] = "msg=rtwMsg_notTraceable&block=pid4/pidstm/pidIdeal/Ki/I_gain";
	/* <S8>/Integral */
	this.urlHashMap["pid4:143"] = "msg=rtwMsg_notTraceable&block=pid4/pidstm/pidIdeal/Ki/Integral";
	/* <S9>/P_Gain */
	this.urlHashMap["pid4:147"] = "msg=rtwMsg_notTraceable&block=pid4/pidstm/pidIdeal/Kp/P_Gain";
	/* <S9>/Proportionals */
	this.urlHashMap["pid4:148"] = "msg=rtwMsg_notTraceable&block=pid4/pidstm/pidIdeal/Kp/Proportionals";
	/* <S10>/I_gain */
	this.urlHashMap["pid4:152"] = "msg=rtwMsg_notTraceable&block=pid4/pidstm/pidIdeal/awm/I_gain";
	/* <S10>/antiwindup */
	this.urlHashMap["pid4:153"] = "msg=rtwMsg_notTraceable&block=pid4/pidstm/pidIdeal/awm/antiwindup";
	/* <S11>/Filtercoeff */
	this.urlHashMap["pid4:158"] = "msg=rtwMsg_notTraceable&block=pid4/pidstm/pidIdeal/filterCoeff/Filtercoeff";
	/* <S11>/I_gain */
	this.urlHashMap["pid4:159"] = "msg=rtwMsg_notTraceable&block=pid4/pidstm/pidIdeal/filterCoeff/I_gain";
	/* <S12>/D_gain */
	this.urlHashMap["pid4:173"] = "pid4.c:126&pid4.h:70";
	/* <S12>/Derivative */
	this.urlHashMap["pid4:174"] = "pid4.c:129&pid4.h:71";
	/* <S13>/I_gain */
	this.urlHashMap["pid4:178"] = "pid4.c:162&pid4.h:76";
	/* <S13>/Integral */
	this.urlHashMap["pid4:179"] = "pid4.c:165&pid4.h:77";
	/* <S14>/P_Gain */
	this.urlHashMap["pid4:183"] = "pid4.c:81&pid4.h:62";
	/* <S14>/Proportionals */
	this.urlHashMap["pid4:184"] = "pid4.c:117&pid4.h:67";
	/* <S15>/I_gain */
	this.urlHashMap["pid4:188"] = "pid4.c:168&pid4.h:78";
	/* <S15>/antiwindup */
	this.urlHashMap["pid4:189"] = "pid4.c:174&pid4.h:80";
	/* <S16>/Filtercoeff */
	this.urlHashMap["pid4:194"] = "pid4.c:138&pid4.h:74";
	/* <S16>/I_gain */
	this.urlHashMap["pid4:195"] = "pid4.c:123&pid4.h:69";
	this.getUrlHash = function(sid) { return this.urlHashMap[sid];}
}
	RTW_Sid2UrlHash.instance = new RTW_Sid2UrlHash();
